name: GitHub-Profile-3D-Contrib

on:
  schedule: # 12:00 AM IST == 6:30 PM UTC
    - cron: "30 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Vedika002
      - name: Set up Git
        run: |
          git config --global user.name "Vedika"
          git config --global user.email "vedikachauhan2002z2gmail.com"
      - name: Commit & Push
        run: |
          git add -A .
          git commit -m "generated"
          git push    
      # - name: Commit & Push
      #   run: |
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git add -A .
      #     git commit -m "generated"
      #     git push
