name: GitHub-Profile-3D-Contrib

on:
  schedule: # 12:00 AM IST == 6:30 PM UTC
    - cron: "30 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.tok-en }}
          USERNAME: Vedika002
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
